name = "padel-app-backend"
main = "worker.js"
compatibility_date = "2024-01-19"

[env.production]
name = "padel-app-backend-prod"

[env.development]
name = "padel-app-backend-dev"

# Add your environment variables here
[vars]
ENVIRONMENT = "production"