name = "padel-app-backend"
main = "worker.js"
compatibility_date = "2024-01-19"

[dev]
port = 8787

[env.production]
name = "padel-app-backend-prod"

[env.development]
name = "padel-app-backend-dev"

# Add your environment variables here
[vars]
ENVIRONMENT = "production"
# BASE_URL = "https://your-domain.com"  # Uncomment and set your production domain

[env.production.vars]
# BASE_URL = "https://your-production-domain.com"

[env.development.vars]
# BASE_URL = "https://your-dev-domain.com"